### ISSUE TITLE
Disable "New" or "Remove" with NestedForm

### ISSUE THREAD

**Issue by isometriq** [z-song/laravel-admin#1027]
The nested form feature ($form->hasMany()) is really powerful.
How should we disable the "New" or "Remove" buttons? Some scenarios would require to not allow these ..or conditionnally

**Comment by isometriq** [comment]
i think i can use ->hasMany( ... )->setView('myview') to use another view and override... but I would strongly suggest that `NestedForm` has a method like `disableNew` and `disableRemove` or one for both.

**Comment by woliveirac** [comment]
@isometriq Would you care to explain how have you done this with a custom view?

**Comment by woliveirac** [comment]
@isometriq Don't worry, i got it, after thinking about your comment, thanks !!

**Comment by woliveirac** [comment]
@isometriq , Hi, well, you can't really use setView on this case because the $form->hasMany is an instance of Form\NestedForm and NestedForm in this case doesn't have a setView method to replace its view. 

So, you still can replace the view for get this done, but, it's gonna be used in your entire admin, you can't actually use a custom view just once, which is my case :C 

Anyway, gonna wait for this. 

Thanks !

**Comment by pcfjojo** [comment]
@z-song Is it possible to disable new button in Hasmany form?

**Comment by mRamadan0101** [comment]
how disable new after add  form ?

**Comment by fhferreira** [comment]
```
$form->hasMany('orders', function (Form\NestedForm $form) {

                        $form->text('id');
                        $form->text('description');
                    })
                        ->disableCreate()
                        ->disableDelete();
```

**Comment by jicksonjohnson** [comment]
@fhferreira is that method working on your side ? I checked but not working.

**Comment by Abbas355** [comment]
Nested form is empty in edit section even data of nested form exist ,so i means i cant edit the nested form ,can any one tell me to edit the nested form
