### ISSUE TITLE
HTML form field size too small

### ISSUE THREAD

**Issue by isometriq** [z-song/laravel-admin#1029]
All the fields are set to `col-sm-8` while the html field is set to `col-sm-6`.

Also its hardcoded in the class as I would expect to be a view that I can override. Not that I can't create my own HTML field, but...

**Comment by isometriq** [comment]
Not sure why, but `setWidth`  is not used at all in that field, all hardcoded

**Comment by z-song** [comment]
Since I do not have much time to put on this repo, and there were too many historical issues,  I did not intend to continue to develop and maintain the previous versions.

I opened a new branch 1.5, which works on Laravel 5.5, the LTS Laravel version. I will works this branch later.

I also developed some practical [extensions](https://github.com/laravel-admin-extensions) for `laravel-admin 1.5`, `laravel-admin 1.5` and these extensions will be released after the release of the laravel 5.5 official version.

**Comment by isometriq** [comment]
Hey these extensions look promising!

I understand your time concern, this project is huge. I will continue creating issues for reference and will keep this in mind.

Do you recommend I use now the 1.5 branch or should I wait for an official tag (likely after 5.5 is released i guess) ?

Thx for the update

**Comment by z-song** [comment]
Thanks for your support!

Any idea of extensions is welcome ;)
