### ISSUE TITLE
select linkage

### ISSUE THREAD

**Issue by naingwin** [z-song/laravel-admin#1452]
- Laravel Version: 5.5.*
- PHP Version: 7
- Laravel-admin: 1.5.*

Can I use select linkage in "Filter" ?

**Comment by z-song** [comment]
Do you mean cascading selects?

**Comment by naingwin** [comment]
Example - I have a lot of "villages" list in db. I want to filter villages by "state" and "townships of selected state".

**Comment by z-song** [comment]
ref http://laravel-admin.org/docs/#/en/model-form-fields?id=select-linkage

**Comment by pcfjojo** [comment]
Is it possible to use **Select-Linkage** with text input ? 
In case when the load api return single record it is possible to set the select to the record is returned but when there needs to be changed the returned value, i could not change it because it looking a rest api result... meaing can not changed the value of select-linkage value.

**Comment by xuanddlftv** [comment]
@z-song 
I use Select Linkage in Filter. As below example:
http://laravel-admin.org/docs/#/en/model-form-fields?id=select-linkage
When I selected province, the default option of city is the first option. How can I set default option is empty?
