### ISSUE TITLE
editable field controller, please answer ASAP

### ISSUE THREAD

**Issue by LanKing** [z-song/laravel-admin#2120]
How to detect, when non-db editable field was edited and make custom actions with it? Also, how to refresh table after that?

**Comment by LanKing** [comment]
found solution, but can't refresh grid after that

**Comment by noogen** [comment]
If you can insert a javascript, this works for me to reload the grid.

```
$.pjax.reload('#pjax-container');
```

**Comment by azaman2204** [comment]
> If you can insert a javascript, this works for me to reload the grid.
> 
> ```
> $.pjax.reload('#pjax-container');
> ```

where can I insert that script so that my grid page reload to refresh when someone update a record into the db. 

I am using pusher trying to refresh my grid page when someone insert a new record into DB using api store. The controller I used is as per php artisan admin: make controller. Don't know where I can inject the reload script. Much appreciated for any help
