### ISSUE TITLE
不在預設 port 頭像路徑問題

### ISSUE THREAD

**Issue by JackKuo-tw** [z-song/laravel-admin#2143]
- Laravel Version: 5.5
- PHP Version: 7.1.16
- Laravel-admin: 1.5.13

### Description:

當我更換預設頭像後無法正確載入，看其路徑僅有 http://localhost/XXXX
但正確來說應該要是 http://localhost:8000/XXXX
也就是本機端開發時用的 port 加上去即可正確顯示

### Steps To Reproduce:

使用非 80 443 port 去開啟網頁

**Comment by noogen** [comment]
This has to do with FlySystem storage configuration flexibility.   It has to be a configuration and not a calculated value because it could be a different value for cloud/cdn storages.   The URL configuration for uploaded file is based on your environment config: https://github.com/z-song/laravel-admin.org/blob/master/config/filesystems.php#L54

Just set it to http://localhost:8000 in your env here: https://github.com/z-song/laravel-admin.org/blob/master/.env#L6

**Comment by JackKuo-tw** [comment]
Thanks, I've learnt a valuable lesson~
