### ISSUE TITLE
How can I add default value in where condition in grid view if filter not selected.

### ISSUE THREAD

**Issue by sujitkv92** [z-song/laravel-admin#2432]
Laravel Version: 5.6.0
PHP Version:7.1
Laravel-admin: 1.5.15

How can I add default where condition in grid view.
I want to pass date if using filter but if not using filter I want use default date in where condition. How can I achieve this.

**Comment by krsmga** [comment]
for conditions
$grid->model()->where('id', '>', 100);

for orders
$grid->model()->orderBy('id', 'desc');

for more informations
http://laravel-admin.org/docs/#/en/model-grid

**Comment by sujitkv92** [comment]
and what if I am using filter with above condition and I am passing id value as 50 here. The condition will become - "where id > 100 and id = 50"

$grid->filter(function($filter){
       $filter->equal('id', 'ID')
});

**Comment by kevinohashi** [comment]
This never seems to have been resolved. I am running into a similar issue. 

I think the goal (this is the goal for me, I can't speak for original issue), setting a default filter when no filters are being passed.

So on new load of the admin page, nothing has been filtered yet, use these default filters. But once a user starts putting their own filters in, those conditions don't apply anymore.

The problem I've run into using the suggested solution $grid->model()->where() is that that condition doesn't even reset. So if a user filters by something that conflicts with it, no results are ever returned. 

For example,

$grid->model()->where('id','>',100)
//we default to showing all results with id > 100.

use filters for id = 50
//no results are returned because we're sending a query that is select * from table where id > 100 and id = 50. This condition can never be true.

So the goal would be use id > 100 when no other filter is present.

**Comment by CHUN-WEI-HSU** [comment]
You can try to set the request value by yourself.
`
    protected function grid()
    {
        if(!request()->has('filter_column_name')){
            request()->merge([
              'filter_column_name' => '0', //Default Value
           ]);

        $grid = new Grid(new  XXXX());
        $grid->filter(....);
    }
/
`
