### ISSUE TITLE
[HELP]: How to remove public from URL

### ISSUE THREAD

**Issue by Muhammadinaam** [z-song/laravel-admin#276]
How can I remove public from URL.

I remove public from URL by using method mentioned in the following link

http://stackoverflow.com/a/32580688/5013099

Above method works for all my projects but when I apply this method to Laravl-Admin. Things do work as expected.

May be z-song/laravel-admin users can tell me how they do it?????

**Comment by isometriq** [comment]
Supposing you are serving the root folder (where .env is) instead of public subfolder, you could add an `/index.php` file with this inside:
```
chdir(__DIR__.'/public');
require __DIR__.'/public/index.php';
```
You will need also to copy `/public/.htaccess` to `/` (where the new index.php file is located) and modify it
```
# Fix for running from app root and in a sub-folder
# Any change done in "public/.htaccess" should be adapted here

<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # IMPORTANT: Change this to the relative path to app root
    # using env var instead of RewriteBase instruction
    #RewriteBase /your-subfolder-here/
    RewriteRule .* - [E=REWRITEBASE:/your-subfolder-here/]

    RewriteCond %{ENV:REWRITEBASE}::%{REQUEST_URI} ^(.*)::\1(.*)$
    RewriteCond %{DOCUMENT_ROOT}%1public/%2 -f
    RewriteCond %{REQUEST_FILENAME} !index.php$
    RewriteRule ^(.*)$ public/$1 [L]

    # Fix JWT from the "Authorization" header removed by Apache
    RewriteCond %{HTTP:Authorization} ^(.*)
    RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

    # Handle special case for the "/" route
    RewriteRule ^$ %{ENV:REWRITEBASE}index.php [L,R=302]

    # Redirect Trailing Slashes...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ %{ENV:REWRITEBASE}$1 [L,R=302]

    # Handle Front Controller...
    RewriteRule ^(.*)$ index.php [L]
</IfModule>
```

Some things to consider...
- .env file, source code and other sensitive file/folder should be protected (htaccess?)
- you may have collisions with routes and subfolders (some may be handled by htaccess)
- you must maintain htaccess

So it works, but not the way intended to be used

Other ways are:
- symbolic link from your documentroot to `/public` folder ..you may need RewriteBase in the `/public/.htaccess` if it's a subfolder
- move the public folder outside the laravel installation and modify the `index.php` to point to the laravel install ..again you may need RewriteBase in the `.htaccess` if it's a subfolder
-

**Comment by isometriq** [comment]
At this moment I have an issue when using a virtual document root (deploying for testing on a remote server with whm userdir).

I discovered that the Admin facade used inside the package creates urls that can't work in that case:
https://github.com/z-song/laravel-admin/issues/992

So my deployed install works, but the admin portion does not work, urls are all relative starting with `/`
