### ISSUE TITLE
feature request: ability to let user reset password

### ISSUE THREAD

**Issue by langeuh** [z-song/laravel-admin#314]
Currently only administrators can create user and their passwords.
It would be great for a user to be able to reset his password

**Comment by z-song** [comment]
Finished this in version 1.3.x-dev, see demo http://120.26.143.106/admin/auth/setting

Enter this page from the top right corner.

Thanks for your suggestion.

**Comment by langeuh** [comment]
Thanks, i was just pulling in the changes.

**Comment by z-song** [comment]
@langeuh  I also finished the feature of upload user avatar, so you may add a column in `admin_users`:

```sql
alter table `admin_users` add column `avatar` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
```

**Comment by langeuh** [comment]
No problem, already saw that. Works great!
By reset password feature, i did mean a 'reset your password' feature on the login screen in case you forgot your password. Maybe later on the roadmap.

But this already helps a lot.

**Comment by renamate** [comment]
yes, I think the same, otherwise you could enable login with the scafolding of laravel auth that already brings it integrated. It does not make sense that in a system there are two tables of users an admin-users and another of users could be that a field would be added to the users table as follows:
````
<?php

use Illuminate\Database\Migrations\Migration;

class AddUserAvatar extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('users', function ($table) {
            $table->string('avatar')->default('users/default.png');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('users', function ($table) {
            $table->dropColumn('avatar');
        });
    }
}
````

This way use the admin Voyager but that administrator does not have a profile manager as flexible as the encore/laravel-admin

Anyway the profile manager only serves users of the admin-user table which is not very practical if one did a scafolding make: auth
Sorry, my english is from Chile

**Comment by sahadatfci** [comment]
My version is 1.6
I didn't found any forgot password feature.
