### ISSUE TITLE
$form->checkbox()多选框问题

### ISSUE THREAD

**Issue by Cuifc** [z-song/laravel-admin#3829]
- Laravel Version: 5.8.31
- PHP Version: 7.1.26
- Laravel-admin: 1.7.5

### Description:
$form->checkbox()->required()多选框使用必填属性后，不把全部的选项选中都会提示“如果要继续，请选择此框”。请修复

**Comment by cawa0505** [comment]
can use $form->checkbox()->rules('required');
rules('required') not use js validation, will use laravel rules after form post and if not validate back to this form page.

but there is a bug in checkbox old empty value return, will send a pr.
the bug is when send nothing to post, the checkbox area will check the item if it's value is 0
![螢幕快照 2019-09-22 下午10 19 44](https://user-images.githubusercontent.com/3434037/65389281-29049380-dd87-11e9-9990-64a492ed5a9d.png)

**Comment by Cuifc** [comment]
> can use $form->checkbox()->rules('required');
> rules('required') not use js validation, will use laravel rules after form post and if not validate back to this form page.
> 
> but there is a bug in checkbox old empty value return, will send a pr.
> the bug is when send nothing to post, the checkbox area will check the item if it's value is 0
> ![螢幕快照 2019-09-22 下午10 19 44](https://user-images.githubusercontent.com/3434037/65389281-29049380-dd87-11e9-9990-64a492ed5a9d.png)

Thanks!
