### ISSUE TITLE
[FEATURE REQUEST] decoupling of Grid, Form from Models

### ISSUE THREAD

**Issue by georgehristov** [z-song/laravel-admin#3950]
Grid and Form components have great features but presently they are tightly coupled with Eloquent models.
Is it planned to decouple them from the model and make that optional?
For instance Grid may accept Collection, Query or Model and Form may have user defined elements and store behavior.

**Comment by DjangoOutplayed** [comment]
Being able to pass a collection to a grid would be indeed very helpful. For example, I have mongo data (for example statistics) that I'd like to aggregate as a ranking table.

I don't want to create a model for that unique case, and I can't use my mongo model either because it doesn't have the fields that I want to display in my ranking table (but I can get them by aggregation).

What I'd like to do is query my data using a mongo aggregation, turn it into a collection (with the fields i want in it) and then pass it to the Grid.

I didn't find a way to do it with current version, but maybe it's already possible ?
