### ISSUE TITLE
Users can not reset their own password

### ISSUE THREAD

**Issue by renamate** [z-song/laravel-admin#399]
How can I configure laravel-admin to use the users table that brings the default scafolding of laravel make:auth and so that each user can reset their own password and login to the system using the email and password.

**Comment by renamate** [comment]
I made a change in the question that had been written in the wrong way

**Comment by z-song** [comment]
Custom passport is not support currently, I'll woking for this.

**Comment by slava-vishnyakov** [comment]
I'd love `php artisan make:auth` compatibility.

**Comment by slava-vishnyakov** [comment]
Actually, it turned out to be surprisingly easy to get `make:auth` compatibility. The biggest problem is that `username` field is not configurable in laravel-admin, otherwise it would've been a few lines of code

Anyway, here's how to make laravel-admin `make:auth` compatible (with password reset and all).

1) copy `vendor/encore/laravel-admin/views/login.blade.php` to `resources/views/admin/login.blade.php`
2) replace `username` with `email` everywhere in that file
3) in config/admin.php replace `admin_users` with `users`
4) in config/auth.php replace `'guard' => 'web',` with `'guard' => 'admin',`
5) copy `cp vendor/encore/laravel-admin/src/Controllers/AuthController.php` to `app/Admin/Controllers/AuthController.php`
6) replace `username` with `email`
7) replace `namespace Encore\Admin\Controllers;` to `namespace App\Admin\Controllers;`
8) replace `admin::login` with `admin.login` (not sure why it's not picking up cusom view)
9) add to `app/Admin/routes.php`:
```php
    $router->get('/auth/login', '\\App\\Admin\\Controllers\\AuthController@getLogin');
    $router->post('/auth/login', '\\App\\Admin\\Controllers\\AuthController@postLogin');
    $router->get('auth/setting', '\\App\\Admin\\Controllers\\AuthController@getSetting');
    $router->put('auth/setting', '\\App\\Admin\\Controllers\\AuthController@putSetting');
```

If `laravel-admin` were to replace `'username'` with something like `config('admin.username_field')` - that would've been much easier! (only config changes)
