### ISSUE TITLE
User Form Needs to ignore Password if not updating

### ISSUE THREAD

**Issue by itsnotyoutoday** [z-song/laravel-admin#3992]
- Laravel Version: 6.x
- PHP Version: 7.3.9
- Laravel-admin: 1.7

### Description:
CRUD for user objects always requires passwords regardless of if that is being updated or not.  This is an undesirable action as we aren't always trying to change user passwords when we modify them.

**Comment by uacode** [comment]
Just make it similar to this https://github.com/z-song/laravel-admin/blob/master/src/Controllers/UserController.php#L103

**Comment by AvionicsBird** [comment]
That is what I have.. it still requires the password

**Comment by AvionicsBird** [comment]
This is how i had to fix it..

First I had to change the password validation to be as so:
```
        $form->password('password', trans('admin.password'))->rules([function($value) {
            if(strlen($value) > 0 && strlen($value) < 6) {
                return false;
            }
        }]);
        $form->password('password_confirmation', trans('admin.password_confirmation'))
            ->rules('sometimes|required_with:password|same:password');
```
Secondly, I had to change the password saving part (as otherwise laravel was bitch about the password field being null) to use the existing model password stored..
```
        $form->saving(function (Form $form) {
            if ($form->password && $form->model()->password != $form->password) {
                $form->password = bcrypt($form->password);
            } else {
                $form->password = $form->model()->password;
            }
        });
```

Now what I don't know.  Is this a laravel 6.x validation issue that sometimes|required won't work on password?  Or is this is a laravel-admin issue?  Furthermore, be interesting to know if there is a way progmatically to remove a particular field from the form save rather than grab from the model to do what I did.

**Comment by nkjackzhang** [comment]
Maybe a better way to solve this issue is moving password field to another form, the origin form only cares about fields of user object except password.
