### ISSUE TITLE
Database Issue

### ISSUE THREAD

**Issue by Younda-E** [z-song/laravel-admin#5201]
- Laravel Version: 7.30.1
- PHP Version: 7.4.8
- Laravel-admin: v1.8.11

### Description:

 QueryException In Connection.php line 671 :
  SQLSTATE[HY000]: General error: 1364 Field 'plate No' doesn't have a default value (SQL: insert into `trucks` (`VIN`, `Model`, `updated_at`, `created_at`) values (6y6y6, jkljko, 2021-01-04 20:08:03, 2021-01-04 20:08:03)).

**Comment by nicelizhi** [comment]
config defalt data for the Field  or nullable

**Comment by SlaraMk** [comment]
I solved this problem but I have other problems
that's it:
1-administrator setting change avatar image not found , but it is in the
public\images folder
2-The second problem is in translation this side menu and anything new I
add will not be translated. How do I solve this problem?
3- Call to undefined method App\Charts\BloodChart::labels()
I got this error when I tried to use chartjs with real data from my
database.
4- when i add readonly field ,this field remains empty in the table , i add
this field  to make only admin can control on it's value . but how can I
save this value in the database when I submit data the field is empty.
5-the QRCode field how do I deal with it in the database? How is its value
saved? because I need to print an invoice and this contains barcode and qr
code.
6- finally how can I export data as .pdf .

can you help me please ?

‫في الثلاثاء، 5 يناير 2021 في 5:47 م تمت كتابة ما يلي بواسطة ‪Steven Liu‬‏
<‪notifications@github.com‬‏>:‬

**Comment by SlaraMk** [comment]
I solved this problem but I have other problems
that's it:
1-administrator setting change avatar image not found , but it is in the
public\images folder
2-The second problem is in translation this side menu and anything new I
add will not be translated. How do I solve this problem?
3- Call to undefined method App\Charts\BloodChart::labels()
I got this error when I tried to use chartjs with real data from my
database.
4- when i add readonly field ,this field remains empty in the table , i add
this field  to make only admin can control on it's value . but how can I
save this value in the database when I submit data the field is empty.
5-the QRCode field how do I deal with it in the database? How is its value
saved? because I need to print an invoice and this contains barcode and qr
code.
6- finally how can I export data as .pdf .

can you help me please ?

**Comment by SlaraMk** [comment]
I solved this problem but I have other problems
that's it:
1-administrator setting change avatar image not found , but it is in the
public\images folder
2-The second problem is in translation this side menu and anything new I
add will not be translated. How do I solve this problem?
3- Call to undefined method App\Charts\BloodChart::labels()
I got this error when I tried to use chartjs with real data from my
database.
4- when i add readonly field ,this field remains empty in the table , i add
this field  to make only admin can control on it's value . but how can I
save this value in the database when I submit data the field is empty.
5-the QRCode field how do I deal with it in the database? How is its value
saved? because I need to print an invoice and this contains barcode and qr
code.
6- finally how can I export data as .pdf .

‫في الأربعاء، 6 يناير 2021 في 5:14 م تمت كتابة ما يلي بواسطة ‪Slara mkawi‬‏
<‪salaramkawi@gmail.com‬‏>:‬

**Comment by SlaraMk** [comment]
I solved this problem but I have other problems
that's it:
1-administrator setting change avatar image not found , but it is in the
public\images folder
2-The second problem is in translation this side menu and anything new I
add will not be translated. How do I solve this problem?
3- Call to undefined method App\Charts\BloodChart::labels()
I got this error when I tried to use chartjs with real data from my
database.
4- when i add readonly field ,this field remains empty in the table , i add
this field  to make only admin can control on it's value . but how can I
save this value in the database when I submit data the field is empty.
5-the QRCode field how do I deal with it in the database? How is its value
saved? because I need to print an invoice and this contains barcode and qr
code.
6- finally how can I export data as .pdf .

I solved this problem but I have other problems

**Comment by SlaraMk** [comment]
that's it:
1-administrator setting change avatar image not found , but it is in the
public\images folder
2-The second problem is in translation this side menu and anything new I
add will not be translated. How do I solve this problem?
3- Call to undefined method App\Charts\BloodChart::labels()
I got this error when I tried to use chartjs with real data from my
database.
4- when i add readonly field ,this field remains empty in the table , i add
this field  to make only admin can control on it's value . but how can I
save this value in the database when I submit data the field is empty.
5-the QRCode field how do I deal with it in the database? How is its value
saved? because I need to print an invoice and this contains barcode and qr
code.
6- finally how can I export data as .pdf .

can you help me please ?

**Comment by SlaraMk** [comment]
I solved this problem but I have other problems
that's it:
1-administrator setting change avatar image not found , but it is in the
public\images folder
2-The second problem is in translation this side menu and anything new I
add will not be translated. How do I solve this problem?
3- Call to undefined method App\Charts\BloodChart::labels()
I got this error when I tried to use chartjs with real data from my
database.
4- when i add readonly field ,this field remains empty in the table , i add
this field  to make only admin can control on it's value . but how can I
save this value in the database when I submit data the field is empty.
5-the QRCode field how do I deal with it in the database? How is its value
saved? because I need to print an invoice and this contains barcode and qr
code.
6- finally how can I export data as .pdf .
