### ISSUE TITLE
filamentphp vs laravel-admin

### ISSUE THREAD

**Issue by gacal** [z-song/laravel-admin#5717]
- Laravel Version: 8.1.2
- PHP Version: 8.2.1
- Laravel-admin: 1.8

### Description:
why don't we use AdminLTE 3x ?

I have been comparing filamentphp with laravel-admin since 1 week. In terms of performance, laravel-admin is 2x faster. I want to continue using it but the view is too old :(

**Comment by alexoleynik0** [comment]
You probably should consider checking some popular forks of this repo ( like [open-admin](https://github.com/open-admin-org/open-admin) ) or different tools altogether ( like [orchid](https://github.com/orchidsoftware/platform) ), because I don't see this project to be actively maintained again after 2+ years of silence, especially with something like whole bunch of outdated dependencies replacement.

**Comment by gacal** [comment]
I did not know these.  Thank you very much.  I guess open-admin is just for me. 👋🙋‍♂️👍🖐️
