### ISSUE TITLE
WHY???? geting the same image when uploading multiple files

### ISSUE THREAD

**Issue by wipit** [z-song/laravel-admin#613]
hi, friends. im trying to upload multiple images with the hasmany function listed in the documentation. it uploads the files ok, but only the first one keeps its original name. and then, when going to edit, it list the exact number of images uploaded, but all of them are the same in the preview. 

in my form() function in the controller, ive pasted:
$form->hasMany('imagenes', function (Form\NestedForm $form) {
                $form->image('nombre', "Imagen");
            });

what i am doing wrong???

thanks in advance, to all of you, smarter people!!!

**Comment by wipit** [comment]
sorry, the relationship goes:

class Auto extends Model {
	
    public function imagenes() {
        return $this->hasMany('App\Imagen', 'auto_id');
    }


class Imagen extends Model {
    public function modelo() {
        return $this->belongsTo('App\Auto', 'auto_id');
    }

**Comment by wipit** [comment]
ok, I kinda figured it out that part of the trouble is in render() in Form/Field/File.
if I add `$this->setElementClass($this->getElementClass().preg_replace("/[^0-9,.]/", "", $this->variables()["name"]));` in line 462, it works, but I bet there is a more elegant way...

someone? ideas?

**Comment by wipit** [comment]
also, I have a problem with getStoreName in the same file. it assigns the names correctly only to the first one in my hasMany images

**Comment by smartymoon** [comment]
i have met same problem.

**Comment by SpinyMan** [comment]
Just add a new random class to each image:
```
$form->hasMany('images', function(Form\NestedForm $nestedForm){
	$nestedForm->image('path')
		->addElementClass(str_shuffle('abcdef1234567890'));
});
```

**Comment by echeveria** [comment]
10х

**Comment by alexoleynik0** [comment]
Run into similar issue but with **custom filed** extended from `Encore\Admin\Form\Field\File`. 

Was using my `$nestedForm->fileCustom()` nested by `->name()` method with callable to generate names for files and it caused the issue, because in the `Encore\Admin\Form\Field\File@prepare` it sets `$this->name = $this->getStoreName($file);` so basically overrides that callable/string you have passed with `name()` method after the first iteration on the NestedForm ($form->hasMany / $form->table) items. 

#### This is what my form looks like:
```php
$form->table('attachments', __('Attachments'), function (Form\NestedForm $nestedForm) {
    // ...
    $nestedForm->fileCustom('file', __('File'))->name(fn ($file) => FileHelper::generateFilename($file));
}
```

#### The form [custom field](https://laravel-admin.org/docs/en/model-form-field-management#Extend%20the%20custom%20field) I've created:
```php
class FileCustom extends \Encore\Admin\Form\Field\File {
    protected function uploadAndDeleteOriginal(UploadedFile $file) {
        // $this->renameIfExists($file); // removed line to disable filename uniqueness check (it's being handled manually)
        // ...
    }
}
```

I was trying many things but eventually only adding new `$nameProvided` property to my extended FileCustom field and using it in overrides of `public function name($name)` and `protected function getStoreName(UploadedFile $file)` helped. 
I make sure that `$this->name` is set on any iteration of NestedForm items in `public function prepare($file)` with the value passed to `->name()` method call. 

Give me know if there's a better approach. Does it need to have the file name in the object after destroy is called? Maybe I'm missing something.

This look's like self made problem, I understand, but the thing that `Encore\Admin\Form\Field\UploadField@renameIfExists` method from `uploadAndDeleteOriginal` kind of not takes into account the `->name()` nesting usage and just silently renames the filename using `generateUniqueName` method is not very obvious and has lead to this whole fuss. 

Maybe it will be better to give some validation level error if specific `->name()` was provided from the form, and the storage already has the file with this name. Something like: 
```php
trait \Encore\Admin\Form\Field\UploadField {
    protected $name = null;
    protected $nameProvided = false;
    // ...
    public function name($name)
    {
        if ($name) {
            $this->name = $name;
            $this->nameProvided = true;
        }
        return $this;
    }
    // ...
    public function renameIfExists(UploadedFile $file)
    {
        if ($this->storage->exists("{$this->getDirectory()}/$this->name")) {
            if (!$this->nameProvided) {
                // TODO: throw validation level error here
            }
            $this->name = $this->generateUniqueName($file);
        }
    }
}
```
This way at least it will be shown to the used/dev that provided name isn't unique and the logic should be changed. Could be helpful if filename preserving is important.
