### ISSUE TITLE
$form->select can't set related to null (URGENT)

### ISSUE THREAD

**Issue by avifatal** [z-song/laravel-admin#833]
Hi, 
I have this `category_id` field in my form, foreign key from `Product` to `ProductCategory` and I can't set it to null :
```
$res = ProductCategory::all()->pluck('name', 'id');
$form->select('category_id', trans('admin::app.category'))->options($res);

// this is the relation from Product to ProductCategiry:
public function category() {
    return $this->belongsTo(ProductCategory::class,'category_id');
}
```
`category_id` is nullable.

this is the data in `$res` :
```
Collection {#386 ▼
  #items: array:5 [▼
  1 => "One"
  2 => "Two"
  3 => "Three"
  4 => "Four"
  5 => "Five"
  ]
]
```
When I click on the `X` in the select, the field actually reset as expected.
in the http request the value is empty:
```
------WebKitFormBoundaryEBHiBJGmKv3CDA06
Content-Disposition: form-data; name="category_id"
```
but in the database category_id is not set to null.

Can you explain what am I doing wrong?
Thanks

**I saw similar questions but the solutions are very "pitfally"**
https://github.com/z-song/laravel-admin/issues/243

**Comment by manyk** [comment]
This happens because the blade is incomplete.

Check **src/Form/Field/Select.php:22** - it should be like this:

`$this->script = "$(\"#{$this->id}\").select2({allowClear: true, placeholder: \"{$this->label}\"});";`

The missing placeholder option triggers Javascript error thus select field not clearing. See the comment from select2 issue: [https://github.com/select2/select2/issues/3497#issuecomment-113501752](https://github.com/select2/select2/issues/3497#issuecomment-113501752)

**Comment by JefferyWong** [comment]
This file are still different between git version and Composer version even version number of them are 1.4.*? How can I update this to the right version?

**Comment by manyk** [comment]
@JefferyWong it feels this repo is quite a mess.
Master branch of this repository is way behind what is active at the moment and very difficult to update - implies lots of cherry picking.
This issue is not pulled in any branch. If you need this fix you might as well modify your code by hand and not rely on Git or Composer.

**Comment by JefferyWong** [comment]
@manyk will this repo get a proper fix? And when?

**Comment by isometriq** [comment]
One cheap trick would to override and insert a `str_replace` in:
`vendor/encore/laravel-admin/views/partials/script.blade.php`

Example:
```
<script data-exec-on-popstate>
    $(function () {
        @foreach($script as $s)
            <?php
                $s = str_replace(
                    '$(\"{$this->getElementClassSelector()}\").select2({allowClear: true});', 
                    '$(\"#{$this->id}\").select2({allowClear: true, placeholder: \"{$this->label}\"});', 
                    $s
                );
            ?>
            {!! $s !!}
        @endforeach
    });
</script>
```

Very temporary ..really don't like this, but it patches the problem until officially fixed without complicated class overrides?

**Comment by isometriq** [comment]
My solution to this was to override the Select field and register it in the bootstrap:

`app/Admin/Extensions/Select.php`
```
<?php

namespace App\Admin\Extensions;

use Encore\Admin\Form\Field\Select as AdminSelect;

class Select extends AdminSelect
{
    public function render()
    {
        if (empty($this->placeholder)) {
            $this->script = '$("'.$this->getElementClassSelector().'").select2({allowClear: false});';
        }
        else {
            $this->script = '$("'.$this->getElementClassSelector().'").select2({allowClear: true, placeholder: '.json_encode($this->placeholder).'});';
            //$this->default = '';
        }

        if ($this->options instanceof \Closure) {
            if ($this->form) {
                $this->options = $this->options->bindTo($this->form->model());
            }

            $this->options(call_user_func($this->options, $this->value));
        }

        $this->options = array_filter($this->options);

        if (!empty($this->placeholder)) {
            $this->options = array_prepend($this->options, ' ', '');
        }

        return parent::render()->with(['options' => $this->options]);
    }
}
```
Note the empty option I'm injecting. I think I am exploiting a bug because select2 is picky about the needed empty <option> tag.

`app/Admin/bootstrap.php`
```
Encore\Admin\Form::extend('select', \App\Admin\Extensions\Select::class);
```

Then I can use the new select field like this:
```
$form->select('fruit')->options(['apple','orange','banana'])->placeholder('Choose something...');
```
When you don't use the placeholder, the selection will be forced (like before).

@z-song Could you take a look into this? Do you prefer pull request?

**Comment by isometriq** [comment]
I prefer to always have a blank placeholder, not propose the first item (i would use `default()` for that purpose). And if I need a placeholder text, I use the `placeholder()` method.

Updated `app/Admin/Extensions/Select.php`
```
<?php

namespace App\Admin\Extensions;

use Encore\Admin\Form\Field\Select as AdminSelect;

class Select extends AdminSelect
{
    public function render()
    {
        if (empty($this->placeholder)) {
            $this->placeholder = '';
        }

        $this->script = '$("'.$this->getElementClassSelector().'").select2({allowClear: true, placeholder: '.json_encode($this->placeholder).'});';

        if ($this->options instanceof \Closure) {
            if ($this->form) {
                $this->options = $this->options->bindTo($this->form->model());
            }

            $this->options(call_user_func($this->options, $this->value));
        }

        $this->options = array_filter($this->options);
        $this->options = array_prepend($this->options, ' ', '');

        return parent::render()->with(['options' => $this->options]);
    }
}
```

This works very well for me.

**Comment by manyk** [comment]
@isometriq you are right. That's overkill.
Best solutions should be the simplest ones.

@JefferyWong I suggest you clone this repository to your GitHub account, make the proper adjustments to the code and use it into your app instead of the official @z-song repository. You can take this path until this issue of laravel-admin is fixed in a future release.

**Comment by isometriq** [comment]
Unless you need to make heavy changes/customizations to the repo (as opposed to what we are dealing with in this issue), I find that cloning or forking the repo would complicate things including maintaining and updating. I don't have lots of experience with forks, so my opinion may be ignorance.

If @z-song accepts pull requests, that would be optimal so that everyone benefits from it?

**Comment by zho** [comment]
@z-song 你明白吗？

**Comment by qcol** [comment]
related to https://github.com/z-song/laravel-admin/issues/867
