### ISSUE TITLE
Grid sorting acting strange, wrong ids

### ISSUE THREAD

**Issue by royduin** [z-song/laravel-admin#858]
I've this grid with 10 records in it:

```
return Admin::grid(Contact::class, function (Grid $grid) {
    $grid->id();
    $grid->name('Name')->display(function(){
        return '<a href="/contacts/'.$this->id.'">'.e($this->name).'</a>';
    })->sortable();

    $grid->customer()->name('Customer')->display(function(){
        return '<a href="/customers/'.$this->customer['id'].'">'.e($this->customer['name']).'</a>';
    })->sortable();

    $grid->phone_number('Phone Number')->display(function(){
        return '<a href="tel:'.e($this->phone_number).'">'.e($this->phone_number).'</a>';
    });
    $grid->email('Email')->display(function(){
        return '<a href="mailto:'.e($this->email).'">'.e($this->email).'</a>';
    });
    $grid->function();
});
```

Where by default it's ordered by ID. So from 1 to 10:

<img width="49" alt="schermafbeelding 2017-05-22 om 14 19 42" src="https://cloud.githubusercontent.com/assets/1703233/26308485/ba7c17f4-3ef9-11e7-9990-e3179116da7f.png">

But when I click on "Customer" to sort it by customer name I'm getting ids which aren't even in de range from 1 to 10:

<img width="40" alt="schermafbeelding 2017-05-22 om 14 19 49" src="https://cloud.githubusercontent.com/assets/1703233/26308495/cf522506-3ef9-11e7-8f07-b8faf26fc63c.png">

Which causes issues when I click on the edit/delete buttons because the ids do not correspond to the column.

I'm running the latest 1.3 version.

**Comment by royduin** [comment]
Any idea @z-song?

**Comment by taimaiduc** [comment]
Currently i know larravel-admin **NOT** support sort in relation.

**Comment by langeuh** [comment]
I have the same problem, and i guess it is indeed not supported.
The problem is clear when you do a dd($this) inside your display() function:

```php
$grid->customer()->name('Customer')->display(function(){
        dd($this);
        return '<a href="/customers/'.$this->customer['id'].'">'.e($this->customer['name']).'</a>';
    })->sortable();
```

you'll see that the 'id' attribute got overwritten with the id of you customer relation, and is no longer the id of the contact.

The resulting array is a mixture of attributes of the model and it's relation due to the sql join.

**Comment by isometriq** [comment]
I was able to create custom ordering and thus allow ordering based on the nested relations value.

My scenario involves a grid of users where i would like ordering by the category (a node tree) parent and order, but could be simply by their name too. Note that I'm showing something different in the grid for the category, the path (name + name of all parents till root).

Inside a Grid callback:
```
$grid->column('category.order', 'Committee')->sortable()->display(function(){
    return $this->category['path']; // category path
});

$sortName = $grid->model()->getSortName();
$sortColumn = request()->input($sortName.'.column');
$sortType = request()->input($sortName.'.type');

switch ($sortColumn)
{
case 'category.order':
    $grid->model()
        ->select('users.*')
        ->join('categories as category', 'category.id', '=', 'users.category_id')
        ->orderByRaw('category.parent_id '.$sortType.', '.$sortColumn.' '.$sortType);
        //->orderBy($sortColumn,$sortType); // could use this for simpler cases
    break;
}
```
So ..not fun to do and involves manually typed joins, but works and allow to do virtually any kind of ordering. The `$sortColumn` depends on what you pass on the `->column` method.

I don't like the joins and this could be enhanced by using the relation methods i think.
Someone help me here?

..and of course, I would like to see that implemented in the original @z-song package

**Comment by isometriq** [comment]
This looks promising
http://laravel-tricks.com/tricks/automatic-join-on-eloquent-models-with-relations-setup

**Comment by isometriq** [comment]
@royduin I don't know why, but I have the problem you identified, with only one of my relations (total 3). If it's like me, you should be to fix with this:
```
$grid->model()->addSelect($grid->model()->getTable().'.*');
```
As @langeuh explained, data is aggregated from various relations. The relation field value will overwrite the main model value where the field name is the same.

The problem is that when ordering the query is a selects SELECT * with a INNER JOIN with relation. MySQL (or Laravel) mashes up every collision and thus ids get overwritten.

The fix I propose is limiting the captured fields.

@z-song this not a feature request, it is a bug

**Comment by isometriq** [comment]
Yeah definitely, the sorting of BelongsTo and HasMany is supported, if check the source code:
vendor/encore/laravel-admin/src/Grid/Model.php
::setRelationSort
::joinParameters

The calls `$this->queries->push( ... )` seems to works partially...

**Comment by isometriq** [comment]
Oh noo.. its the same issue as this ..problem with camel case on relations
https://github.com/z-song/laravel-admin/issues/946

Also lower case makes the sortable work (adds inner join and orderby clauses), but in the callback `->display(function($value){ return '...';})` the relation array key are without the underscore. Probably Laravel throwing something different because it recognizes camel case.

**Comment by oopmvc** [comment]
Can we add a Natural sort 

How can i get 'natural order' in 'Eloquent ORM'? In table I have column 'text' (string).
Normal order: Model::orderBy('text')

'value 1'
'value 12'
'value 23'  
'value 3'
'value 8'
I need this:

'value 1'
'value 3'
'value 8'
'value 12'
'value 23'  
Any ideas?

Model::orderBy(DB::raw('LENGTH(text), text'));

- Do we have Column.php functions for this? -- any way overwrite Column.php ?

**Comment by naingwin** [comment]
facing with same problem, how can I fix?

**Comment by blackcolt** [comment]
Same here.
